CREATE TABLE [dbo].[UserTask]
(
	[UserTaskId] INT IDENTITY NOT NULL, 
	[TaskId] INT NOT NULL, 
	[UserId] INT NOT NULL, 
	[StateId] INT NOT NULL

	CONSTRAINT [PK_UserTask] PRIMARY KEY ([UserTaskId])
	CONSTRAINT [FK_UserTask_To_UserProfile] FOREIGN KEY ([UserId]) REFERENCES [UserProfile]([UserId]) ON DELETE CASCADE ON UPDATE CASCADE 
)
