CREATE TABLE [dbo].[UserTasks]
(
	[UserTaskId] INT IDENTITY NOT NULL, 
	[TaskId] INT NOT NULL, 
	[UserId] INT NOT NULL, 
	[StateId] INT NOT NULL

	CONSTRAINT [PK_UserTask] PRIMARY KEY ([UserTaskId])
	CONSTRAINT [FK_UserTask_To_UserProfile] FOREIGN KEY ([UserId]) REFERENCES [UserProfiles]([UserId]) ON DELETE CASCADE ON UPDATE CASCADE 
	CONSTRAINT [FK_UserTask_To_TaskState] FOREIGN KEY ([StateId]) REFERENCES [TaskStates]([StateId]) ON DELETE CASCADE ON UPDATE CASCADE
	CONSTRAINT [FK_UserTask_To_Task] FOREIGN KEY ([TaskId]) REFERENCES [Tasks]([TaskId]) ON DELETE CASCADE ON UPDATE CASCADE
)
