//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIMS.EF.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTrack
    {
        public int TaskTrackId { get; set; }
        public int UserTaskId { get; set; }
        public System.DateTime TrackDate { get; set; }
        public string TrackNote { get; set; }
    
        public virtual UserTask UserTask { get; set; }
    }
}
