//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIMS.EF.DAL.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaskTrack
    {
        [Key]
        public int TaskTrackId { get; set; }
        public int UserTaskId { get; set; }
        public System.DateTime TrackDate { get; set; }
        public string TrackNote { get; set; }
    
        public virtual UserTask UserTask { get; set; }
    }
}
